#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

use CliClack\Lib\App;
use CliClack\App\Command\HelloController;

// Проверяем тип интерфейса, который использует php
if (php_sapi_name() !== 'cli') {
    exit;
}

$app = new App();

$app->registerController('hello', new HelloController($app));

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->getPrinter()->display("usage: minicli hello [ your-name ]");
});

$app->runCommand($argv);
