#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';
use CliClack\Lib\App;

// Проверяем тип интерфейса, который использует php
if (php_sapi_name() !== 'cli') {
    exit;
}

$app = new App();

$app->registerCommand('hello', function (array $argv) use ($app) {
    $name = isset ($argv[2]) ? $argv[2] : "World";
    $app->getPrinter()->display("Hello $name!!!");
});

$app->runCommand($argv);
